// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH3U18vZP2mgvm1NAQYubcQeIj0iF8SyY',
    appId: '1:692188153936:web:2c540fca753989484b6955',
    messagingSenderId: '692188153936',
    projectId: 'chat-app-e31f5',
    authDomain: 'chat-app-e31f5.firebaseapp.com',
    storageBucket: 'chat-app-e31f5.appspot.com',
    measurementId: 'G-7HJYNW8W11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Q5GaD2IuvM58BFpNKLbRqUBPLbhWqC0',
    appId: '1:692188153936:android:dcb55af3d643bf914b6955',
    messagingSenderId: '692188153936',
    projectId: 'chat-app-e31f5',
    storageBucket: 'chat-app-e31f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnKwLXsx8WjWb3iIRPetDSCB73-JdeNu0',
    appId: '1:692188153936:ios:e65aec4086104ae04b6955',
    messagingSenderId: '692188153936',
    projectId: 'chat-app-e31f5',
    storageBucket: 'chat-app-e31f5.appspot.com',
    iosClientId: '692188153936-hj2ecqfavlbt8nhsbrjng82drf6045t4.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
